[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[MiddleEarth]
title = "Middle-earth & J.R.R. Tolkien Blog"
url = "https://middle-earth.xenite.org"
entrySelector = "#main article"
titleSelector = "header h2 a"
linkSelector = "*"
contentSelector = ".entry-content p"
dateSelector = "header .entry-meta .posted-on a time.entry-date"
dateFormat = "PP"
